"""initial schema

Revision ID: 286fe1620952
Revises: 
Create Date: 2026-09-07 14:10:24.863900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286fe1620952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('matched_entity_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_number'), 'seasons', ['number'], unique=True)
    op.create_table('talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('episode_code', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('article_pdf_paths', sa.JSON(), nullable=False),
    sa.Column('presentation_pdf_paths', sa.JSON(), nullable=False),
    sa.Column('source_language', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talks_episode_code'), 'talks', ['episode_code'], unique=False)
    op.create_index(op.f('ix_talks_season_id'), 'talks', ['season_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('definition', 'theorem', 'property', 'problem', name='entitykind'), nullable=False),
    sa.Column('talk_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.Text(), nullable=True),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('statement_ru', sa.Text(), nullable=True),
    sa.Column('statement_en', sa.Text(), nullable=True),
    sa.Column('proof_ru', sa.Text(), nullable=True),
    sa.Column('proof_en', sa.Text(), nullable=True),
    sa.Column('is_machine_translated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['talk_id'], ['talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_index(op.f('ix_entities_slug'), 'entities', ['slug'], unique=True)
    op.create_index(op.f('ix_entities_talk_id'), 'entities', ['talk_id'], unique=False)
    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_links_from_entity_id'), 'entity_links', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_links_to_entity_id'), 'entity_links', ['to_entity_id'], unique=False)
    op.create_table('review_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cards_entity_id'), 'review_cards', ['entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_cards_entity_id'), table_name='review_cards')
    op.drop_table('review_cards')
    op.drop_index(op.f('ix_entity_links_to_entity_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_from_entity_id'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_entities_talk_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_slug'), table_name='entities')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_talks_season_id'), table_name='talks')
    op.drop_index(op.f('ix_talks_episode_code'), table_name='talks')
    op.drop_table('talks')
    op.drop_index(op.f('ix_seasons_number'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('search_queries')
    # ### end Alembic commands ###
