"""entity source citation

Revision ID: f192e54db63d
Revises: bb9347b1313f
Create Date: 2026-09-07 19:14:59.462399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f192e54db63d'
down_revision: Union[str, Sequence[str], None] = 'bb9347b1313f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('source_citation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'source_citation')
    # ### end Alembic commands ###
